package com.fisincorporated.languagetutorial.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.fisincorporated.languagetutorial.db.LanguageCode;
import com.fisincorporated.languagetutorial.db.Teacher;
import com.fisincorporated.languagetutorial.db.TeacherLanguage;
import com.fisincorporated.languagetutorial.db.ClassName;
import com.fisincorporated.languagetutorial.db.Lesson;
import com.fisincorporated.languagetutorial.db.LanguagePhrase;
import com.fisincorporated.languagetutorial.db.LanguageXref;
import com.fisincorporated.languagetutorial.db.LessonPhrase;
import com.fisincorporated.languagetutorial.db.CompoundPhrase;

import com.fisincorporated.languagetutorial.db.LanguageCodeDao;
import com.fisincorporated.languagetutorial.db.TeacherDao;
import com.fisincorporated.languagetutorial.db.TeacherLanguageDao;
import com.fisincorporated.languagetutorial.db.ClassNameDao;
import com.fisincorporated.languagetutorial.db.LessonDao;
import com.fisincorporated.languagetutorial.db.LanguagePhraseDao;
import com.fisincorporated.languagetutorial.db.LanguageXrefDao;
import com.fisincorporated.languagetutorial.db.LessonPhraseDao;
import com.fisincorporated.languagetutorial.db.CompoundPhraseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig languageCodeDaoConfig;
    private final DaoConfig teacherDaoConfig;
    private final DaoConfig teacherLanguageDaoConfig;
    private final DaoConfig classNameDaoConfig;
    private final DaoConfig lessonDaoConfig;
    private final DaoConfig languagePhraseDaoConfig;
    private final DaoConfig languageXrefDaoConfig;
    private final DaoConfig lessonPhraseDaoConfig;
    private final DaoConfig compoundPhraseDaoConfig;

    private final LanguageCodeDao languageCodeDao;
    private final TeacherDao teacherDao;
    private final TeacherLanguageDao teacherLanguageDao;
    private final ClassNameDao classNameDao;
    private final LessonDao lessonDao;
    private final LanguagePhraseDao languagePhraseDao;
    private final LanguageXrefDao languageXrefDao;
    private final LessonPhraseDao lessonPhraseDao;
    private final CompoundPhraseDao compoundPhraseDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        languageCodeDaoConfig = daoConfigMap.get(LanguageCodeDao.class).clone();
        languageCodeDaoConfig.initIdentityScope(type);

        teacherDaoConfig = daoConfigMap.get(TeacherDao.class).clone();
        teacherDaoConfig.initIdentityScope(type);

        teacherLanguageDaoConfig = daoConfigMap.get(TeacherLanguageDao.class).clone();
        teacherLanguageDaoConfig.initIdentityScope(type);

        classNameDaoConfig = daoConfigMap.get(ClassNameDao.class).clone();
        classNameDaoConfig.initIdentityScope(type);

        lessonDaoConfig = daoConfigMap.get(LessonDao.class).clone();
        lessonDaoConfig.initIdentityScope(type);

        languagePhraseDaoConfig = daoConfigMap.get(LanguagePhraseDao.class).clone();
        languagePhraseDaoConfig.initIdentityScope(type);

        languageXrefDaoConfig = daoConfigMap.get(LanguageXrefDao.class).clone();
        languageXrefDaoConfig.initIdentityScope(type);

        lessonPhraseDaoConfig = daoConfigMap.get(LessonPhraseDao.class).clone();
        lessonPhraseDaoConfig.initIdentityScope(type);

        compoundPhraseDaoConfig = daoConfigMap.get(CompoundPhraseDao.class).clone();
        compoundPhraseDaoConfig.initIdentityScope(type);

        languageCodeDao = new LanguageCodeDao(languageCodeDaoConfig, this);
        teacherDao = new TeacherDao(teacherDaoConfig, this);
        teacherLanguageDao = new TeacherLanguageDao(teacherLanguageDaoConfig, this);
        classNameDao = new ClassNameDao(classNameDaoConfig, this);
        lessonDao = new LessonDao(lessonDaoConfig, this);
        languagePhraseDao = new LanguagePhraseDao(languagePhraseDaoConfig, this);
        languageXrefDao = new LanguageXrefDao(languageXrefDaoConfig, this);
        lessonPhraseDao = new LessonPhraseDao(lessonPhraseDaoConfig, this);
        compoundPhraseDao = new CompoundPhraseDao(compoundPhraseDaoConfig, this);

        registerDao(LanguageCode.class, languageCodeDao);
        registerDao(Teacher.class, teacherDao);
        registerDao(TeacherLanguage.class, teacherLanguageDao);
        registerDao(ClassName.class, classNameDao);
        registerDao(Lesson.class, lessonDao);
        registerDao(LanguagePhrase.class, languagePhraseDao);
        registerDao(LanguageXref.class, languageXrefDao);
        registerDao(LessonPhrase.class, lessonPhraseDao);
        registerDao(CompoundPhrase.class, compoundPhraseDao);
    }
    
    public void clear() {
        languageCodeDaoConfig.getIdentityScope().clear();
        teacherDaoConfig.getIdentityScope().clear();
        teacherLanguageDaoConfig.getIdentityScope().clear();
        classNameDaoConfig.getIdentityScope().clear();
        lessonDaoConfig.getIdentityScope().clear();
        languagePhraseDaoConfig.getIdentityScope().clear();
        languageXrefDaoConfig.getIdentityScope().clear();
        lessonPhraseDaoConfig.getIdentityScope().clear();
        compoundPhraseDaoConfig.getIdentityScope().clear();
    }

    public LanguageCodeDao getLanguageCodeDao() {
        return languageCodeDao;
    }

    public TeacherDao getTeacherDao() {
        return teacherDao;
    }

    public TeacherLanguageDao getTeacherLanguageDao() {
        return teacherLanguageDao;
    }

    public ClassNameDao getClassNameDao() {
        return classNameDao;
    }

    public LessonDao getLessonDao() {
        return lessonDao;
    }

    public LanguagePhraseDao getLanguagePhraseDao() {
        return languagePhraseDao;
    }

    public LanguageXrefDao getLanguageXrefDao() {
        return languageXrefDao;
    }

    public LessonPhraseDao getLessonPhraseDao() {
        return lessonPhraseDao;
    }

    public CompoundPhraseDao getCompoundPhraseDao() {
        return compoundPhraseDao;
    }

}
