package com.fisincorporated.languagetutorial.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table LANGUAGE_CODE.
 */
public class LanguageCode {

    private Long id;
    /** Not-null value. */
    private String languageName;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public LanguageCode() {
    }

    public LanguageCode(Long id) {
        this.id = id;
    }

    public LanguageCode(Long id, String languageName) {
        this.id = id;
        this.languageName = languageName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getLanguageName() {
        return languageName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLanguageName(String languageName) {
        this.languageName = languageName;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
