package com.fisincorporated.languagetutorial.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.fisincorporated.languagetutorial.db.CompoundPhrase;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table COMPOUND_PHRASE.
*/
public class CompoundPhraseDao extends AbstractDao<CompoundPhrase, Long> {

    public static final String TABLENAME = "COMPOUND_PHRASE";

    /**
     * Properties of entity CompoundPhrase.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CompoundPhraseId = new Property(1, long.class, "compoundPhraseId", false, "COMPOUND_PHRASE_ID");
        public final static Property PhraseOrder = new Property(2, int.class, "phraseOrder", false, "PHRASE_ORDER");
        public final static Property LanguagePhraseId = new Property(3, Long.class, "languagePhraseId", false, "LANGUAGE_PHRASE_ID");
        public final static Property PhraseInterval = new Property(4, float.class, "phraseInterval", false, "PHRASE_INTERVAL");
    };

    private DaoSession daoSession;

    private Query<CompoundPhrase> languagePhrase_LanguagePhraseToManyCompoundPhrasesQuery;

    public CompoundPhraseDao(DaoConfig config) {
        super(config);
    }
    
    public CompoundPhraseDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'COMPOUND_PHRASE' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'COMPOUND_PHRASE_ID' INTEGER NOT NULL ," + // 1: compoundPhraseId
                "'PHRASE_ORDER' INTEGER NOT NULL ," + // 2: phraseOrder
                "'LANGUAGE_PHRASE_ID' INTEGER," + // 3: languagePhraseId
                "'PHRASE_INTERVAL' REAL NOT NULL );"); // 4: phraseInterval
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_COMPOUND_PHRASE_COMPOUND_PHRASE_ID ON COMPOUND_PHRASE" +
                " (COMPOUND_PHRASE_ID);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_COMPOUND_PHRASE_LANGUAGE_PHRASE_ID ON COMPOUND_PHRASE" +
                " (LANGUAGE_PHRASE_ID);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_COMPOUND_PHRASE_COMPOUND_PHRASE_ID_PHRASE_ORDER ON COMPOUND_PHRASE" +
                " (COMPOUND_PHRASE_ID,PHRASE_ORDER);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'COMPOUND_PHRASE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CompoundPhrase entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCompoundPhraseId());
        stmt.bindLong(3, entity.getPhraseOrder());
 
        Long languagePhraseId = entity.getLanguagePhraseId();
        if (languagePhraseId != null) {
            stmt.bindLong(4, languagePhraseId);
        }
        stmt.bindDouble(5, entity.getPhraseInterval());
    }

    @Override
    protected void attachEntity(CompoundPhrase entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public CompoundPhrase readEntity(Cursor cursor, int offset) {
        CompoundPhrase entity = new CompoundPhrase( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // compoundPhraseId
            cursor.getInt(offset + 2), // phraseOrder
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // languagePhraseId
            cursor.getFloat(offset + 4) // phraseInterval
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CompoundPhrase entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCompoundPhraseId(cursor.getLong(offset + 1));
        entity.setPhraseOrder(cursor.getInt(offset + 2));
        entity.setLanguagePhraseId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setPhraseInterval(cursor.getFloat(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(CompoundPhrase entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(CompoundPhrase entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "languagePhraseToManyCompoundPhrases" to-many relationship of LanguagePhrase. */
    public List<CompoundPhrase> _queryLanguagePhrase_LanguagePhraseToManyCompoundPhrases(long compoundPhraseId) {
        synchronized (this) {
            if (languagePhrase_LanguagePhraseToManyCompoundPhrasesQuery == null) {
                QueryBuilder<CompoundPhrase> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.CompoundPhraseId.eq(null));
                languagePhrase_LanguagePhraseToManyCompoundPhrasesQuery = queryBuilder.build();
            }
        }
        Query<CompoundPhrase> query = languagePhrase_LanguagePhraseToManyCompoundPhrasesQuery.forCurrentThread();
        query.setParameter(0, compoundPhraseId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getLanguagePhraseDao().getAllColumns());
            builder.append(" FROM COMPOUND_PHRASE T");
            builder.append(" LEFT JOIN LANGUAGE_PHRASE T0 ON T.'LANGUAGE_PHRASE_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected CompoundPhrase loadCurrentDeep(Cursor cursor, boolean lock) {
        CompoundPhrase entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        LanguagePhrase compoundPhraseToOneLanguagePhrase = loadCurrentOther(daoSession.getLanguagePhraseDao(), cursor, offset);
        entity.setCompoundPhraseToOneLanguagePhrase(compoundPhraseToOneLanguagePhrase);

        return entity;    
    }

    public CompoundPhrase loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<CompoundPhrase> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<CompoundPhrase> list = new ArrayList<CompoundPhrase>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<CompoundPhrase> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<CompoundPhrase> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
