package com.fisincorporated.languagetutorial.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.fisincorporated.languagetutorial.db.LanguageXref;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table LANGUAGE_XREF.
*/
public class LanguageXrefDao extends AbstractDao<LanguageXref, Long> {

    public static final String TABLENAME = "LANGUAGE_XREF";

    /**
     * Properties of entity LanguageXref.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TeacherId = new Property(1, long.class, "teacherId", false, "TEACHER_ID");
        public final static Property TeacherLanguageId = new Property(2, long.class, "teacherLanguageId", false, "TEACHER_LANGUAGE_ID");
        public final static Property LearningPhraseId = new Property(3, long.class, "learningPhraseId", false, "LEARNING_PHRASE_ID");
        public final static Property KnownPhraseId = new Property(4, Long.class, "knownPhraseId", false, "KNOWN_PHRASE_ID");
    };

    private DaoSession daoSession;

    private Query<LanguageXref> teacher_TeacherToLanguageXrefsQuery;
    private Query<LanguageXref> teacherLanguage_TeacherLanguageToManyLanguageXrefsQuery;

    public LanguageXrefDao(DaoConfig config) {
        super(config);
    }
    
    public LanguageXrefDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'LANGUAGE_XREF' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'TEACHER_ID' INTEGER NOT NULL ," + // 1: teacherId
                "'TEACHER_LANGUAGE_ID' INTEGER NOT NULL ," + // 2: teacherLanguageId
                "'LEARNING_PHRASE_ID' INTEGER NOT NULL ," + // 3: learningPhraseId
                "'KNOWN_PHRASE_ID' INTEGER);"); // 4: knownPhraseId
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_LANGUAGE_XREF_TEACHER_ID ON LANGUAGE_XREF" +
                " (TEACHER_ID);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_LANGUAGE_XREF_TEACHER_LANGUAGE_ID ON LANGUAGE_XREF" +
                " (TEACHER_LANGUAGE_ID);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_LANGUAGE_XREF_LEARNING_PHRASE_ID ON LANGUAGE_XREF" +
                " (LEARNING_PHRASE_ID);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_LANGUAGE_XREF_KNOWN_PHRASE_ID ON LANGUAGE_XREF" +
                " (KNOWN_PHRASE_ID);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'LANGUAGE_XREF'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, LanguageXref entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getTeacherId());
        stmt.bindLong(3, entity.getTeacherLanguageId());
        stmt.bindLong(4, entity.getLearningPhraseId());
 
        Long knownPhraseId = entity.getKnownPhraseId();
        if (knownPhraseId != null) {
            stmt.bindLong(5, knownPhraseId);
        }
    }

    @Override
    protected void attachEntity(LanguageXref entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public LanguageXref readEntity(Cursor cursor, int offset) {
        LanguageXref entity = new LanguageXref( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // teacherId
            cursor.getLong(offset + 2), // teacherLanguageId
            cursor.getLong(offset + 3), // learningPhraseId
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // knownPhraseId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, LanguageXref entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTeacherId(cursor.getLong(offset + 1));
        entity.setTeacherLanguageId(cursor.getLong(offset + 2));
        entity.setLearningPhraseId(cursor.getLong(offset + 3));
        entity.setKnownPhraseId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(LanguageXref entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(LanguageXref entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "teacherToLanguageXrefs" to-many relationship of Teacher. */
    public List<LanguageXref> _queryTeacher_TeacherToLanguageXrefs(long teacherId) {
        synchronized (this) {
            if (teacher_TeacherToLanguageXrefsQuery == null) {
                QueryBuilder<LanguageXref> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.TeacherId.eq(null));
                queryBuilder.orderRaw("TEACHER_LANGUAGE_ID ASC");
                teacher_TeacherToLanguageXrefsQuery = queryBuilder.build();
            }
        }
        Query<LanguageXref> query = teacher_TeacherToLanguageXrefsQuery.forCurrentThread();
        query.setParameter(0, teacherId);
        return query.list();
    }

    /** Internal query to resolve the "TeacherLanguageToManyLanguageXrefs" to-many relationship of TeacherLanguage. */
    public List<LanguageXref> _queryTeacherLanguage_TeacherLanguageToManyLanguageXrefs(long teacherLanguageId) {
        synchronized (this) {
            if (teacherLanguage_TeacherLanguageToManyLanguageXrefsQuery == null) {
                QueryBuilder<LanguageXref> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.TeacherLanguageId.eq(null));
                teacherLanguage_TeacherLanguageToManyLanguageXrefsQuery = queryBuilder.build();
            }
        }
        Query<LanguageXref> query = teacherLanguage_TeacherLanguageToManyLanguageXrefsQuery.forCurrentThread();
        query.setParameter(0, teacherLanguageId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getTeacherDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getLanguagePhraseDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getLanguagePhraseDao().getAllColumns());
            builder.append(" FROM LANGUAGE_XREF T");
            builder.append(" LEFT JOIN TEACHER T0 ON T.'TEACHER_ID'=T0.'_id'");
            builder.append(" LEFT JOIN LANGUAGE_PHRASE T1 ON T.'LEARNING_PHRASE_ID'=T1.'_id'");
            builder.append(" LEFT JOIN LANGUAGE_PHRASE T2 ON T.'KNOWN_PHRASE_ID'=T2.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected LanguageXref loadCurrentDeep(Cursor cursor, boolean lock) {
        LanguageXref entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Teacher teacher = loadCurrentOther(daoSession.getTeacherDao(), cursor, offset);
         if(teacher != null) {
            entity.setTeacher(teacher);
        }
        offset += daoSession.getTeacherDao().getAllColumns().length;

        LanguagePhrase languageXrefToOneLearningLanguagePhrase = loadCurrentOther(daoSession.getLanguagePhraseDao(), cursor, offset);
         if(languageXrefToOneLearningLanguagePhrase != null) {
            entity.setLanguageXrefToOneLearningLanguagePhrase(languageXrefToOneLearningLanguagePhrase);
        }
        offset += daoSession.getLanguagePhraseDao().getAllColumns().length;

        LanguagePhrase languageXrefToOneKnownLanguagePhrase = loadCurrentOther(daoSession.getLanguagePhraseDao(), cursor, offset);
        entity.setLanguageXrefToOneKnownLanguagePhrase(languageXrefToOneKnownLanguagePhrase);

        return entity;    
    }

    public LanguageXref loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<LanguageXref> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<LanguageXref> list = new ArrayList<LanguageXref>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<LanguageXref> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<LanguageXref> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
